---
title: "02_Carto. Cartographie statistique 1."
author: "R. Leconte"
date: "10/01/2022"
output: html_document
---



https://www.data.gouv.fr/fr/datasets/decoupage-administratif-communal-francais-issu-d-openstreetmap/


```{r pkg}
library(sf)
library(mapview)
library(mapsf)
library(viridis)
```

# 1. Ajouter la géométrie aux données


```{r prep}
# charger la géométrie avec sf
comsf <- st_read(dsn = "communes-20220101.shp", 
                  stringsAsFactors = F)

# filtrer comme un data frame
comsf_avignon <- comsf %>% 
  filter(insee %in% uu_avignon$CODGEO) %>% 
  rename(CODGEO = insee)

# interroger le système de coordoonées 
st_crs(comsf_avignon)

# projeter le fond de carte dans le référentiel Lambert93 (adapté pour la France)
comsf_avignon <- st_transform(comsf_avignon, crs = 2154)

# visualiser la géométrie
plot(comsf_avignon$geometry)

# joindre les données attributaires
comsf_avignon <- left_join(comsf_avignon, pvr_avignon, by = "CODGEO")

comsf_avignon <- left_join(comsf_avignon, disp_avignon_ens, by = "CODGEO")
comsf_avignon_mono <- left_join(comsf_avignon, disp_avignon_mono, by = "CODGEO")

# vérifier qu'il s'agit toujours d'un objet sf...
class(comsf_avignon)
class(comsf_avignon_mono)
# sinon, réassigner
comsf_avignon <- st_sf(comsf_avignon)


```

# 1 bis: Cartographier sans réfléchir

```{r mapview}

# pour le meilleur
mapview(comsf_avignon_mono, zcol = "TYM5Q118")

# et le pire
mapview(comsf_avignon, zcol = "NBPERS18")

```




# 2. Carte de stock

```{r stock}

mf_map(comsf_avignon, col = "grey80", border = "grey50")
mf_map(comsf_avignon, 
       var = "NBPERS18", 
       type = "prop", 
       border = "white", 
       col = "darkblue", 
      inches = 0.3, 
      symbol = "circle",
       leg_title = "Population communale",
      add= TRUE)
mf_layout(title = "Populations communales de l'unité urbaine d'Avignon (2018)", 
    credits = "Auteur: R. Leconte, 2022. Données: INSEE, Filosofi, 2018",
    arrow = FALSE)



```


# 3. Carte de ratio

```{r ratio}

mf_map(comsf_avignon, 
       var = "Q3_Q1", 
       type = "choro", 
       breaks = "quantile", # "fixed", "sd", "equal", "pretty", "quantile", "kmeans", "hclust", "bclust", "fisher", "jenks" and "dpih"
       nbreaks = 6, 
       pal = viridis(6), 
       border = "grey50", 
       leg_title = "Taux de pauvreté au seuil de 60%\n(discrétisation 6 quantiles)")
mf_layout(title = "La pauvreté dans l'unité urbaine de Avignon (2018)", 
    credits = "Auteur: R. Leconte, 2022. Données: INSEE, Filosofi, 2018",
    arrow = FALSE)
# mf_theme("default") # default, ink, dark, agolalight, candy,darkula, iceberg, green, nevermind, jsk or barcelona



# De l'importance des choix de discrétisation

mf_map(comsf_avignon, 
       var = "TP6018", 
       type = "choro", 
       breaks = "equal", 
       nbreaks = 3,
       pal = viridis(3), 
       border = "grey50", 
       leg_title = "Taux de pauvreté au seuil de 60%\n(discrétisation 6 quantiles)")
mf_layout(title = "La pauvreté dans l'unité urbaine de Avignon (2018)", 
    credits = "Auteur: R. Leconte, 2022. Données: INSEE, Filosofi, 2018",
    arrow = FALSE)

```


# 4. Carte de typo

```{r typo}
# nouvelle variable quali
comsf_avignon$dept <- substr(comsf_avignon$CODGEO, 1,2)


mf_map(comsf_avignon, 
       var = "dept", 
       type = "typo", 
       pal = "Zissou 1",
       border = "grey50", 
       leg_pos = NA)
mf_layout(title = "Départements des communes de l'UU de Avignon", 
    credits = "Auteur: R. Leconte, 2022. Données: INSEE, Filosofi, 2018",
    arrow = FALSE)
# améliorer la légende
mf_legend(type = "typo", pos = "topright", val = c("Bouches-du-Rhônes", "Gard", "Vaucluse"), pal = "Zissou 1", title = "Départements", cex = 0.5)

```


# 5. Exporter

```{r export}

# Choisir le format d'export
pdf("Carte.pdf", # Emplacement et nom du fichier
width=7, #largeur en pouces - une page A4 fait environ 8 x 11
height=7 , #hauteur en pouces
useDingbats=FALSE)
# Ou bien 
png("img/Carte.png", # Emplacement et nom du fichier
    width=7, #largeur en pouces
    height=7 , #hauteur en pouces
    res = 300) # résolution en pixels par pouce (DPI) - 300 est idéal pour imprimer



# Puis on place toutes les lignes de code pour produire la carte
mf_map(comsf_avignon, 
       var = "dept", 
       type = "typo", 
       pal = "Zissou 1",
       border = "grey50", 
       leg_pos = NA)
mf_layout(title = "Départements des communes de l'UU de Avignon", 
    credits = "Auteur: R. Leconte, 2022. Données: INSEE, Filosofi, 2018",
    arrow = FALSE)
# améliorer la légende
mf_legend(type = "typo", pos = "topright", val = c("Bouches-du-Rhônes", "Gard", "Vaucluse"), pal = "Zissou 1", title = "Départements", cex = 0.5)


#On cloture le fichier crée

dev.off()

```
